---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
        name: Prevent errors on case-insensitive filesystems
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Ensure file ends with one newline

      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format python files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: [
          --disable=MD013
        ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        name: Lint python code
        args: ["--fix"]
